import "../src/css/normalize.css";
import "../src/css/variables.css";
import "../src/css/estilosStartup.css";
import "../src/css/header.css";
import "../src/css/hero.css";
import "../src/css/caracteristicas.css";
import "../src/css/precios.css"
import "../src/css/footer.css";
import "../src/js/video.js";
import "../src/js/slideshow.js";
import "../src/js/caracteristicas.js";